IntroduccionRazor/Pages/Arreglos.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace IntroduccionRazor.Pages
{
    public class ArreglosModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

IntroduccionRazor/Pages/ArreglosNum.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace IntroduccionRazor.Pages
{
    public class ArreglosNumModel : PageModel
    {
        public int[] numeros { get; set; }
        public void OnGet()
        {
            Random random = new Random();
            numeros = new int[20];

            for (int i = 0; i < 20; i++)
            {
                numeros[i] = random.Next(0, 101);
            }
        }
    }
}

IntroduccionRazor/Pages/Ciclos.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace IntroduccionRazor.Pages
{
    public class CiclosModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

IntroduccionRazor/Pages/Condicionales.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace IntroduccionRazor.Pages
{
    public class CondicionalesModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

IntroduccionRazor/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace IntroduccionRazor.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

IntroduccionRazor/Pages/Expresion.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace IntroduccionRazor.Pages
{
    public class ExpresionModel : PageModel
    {
        [BindProperty]
        public double a { get; set; }

        [BindProperty]
        public double b { get; set; }

        [BindProperty]
        public double x { get; set; }

        [BindProperty]
        public double y { get; set; }

        [BindProperty]
        public int n { get; set; }

        public double totalEsperado { get; set; }

        public void OnPost()
        {
            double valorA = Convert.ToDouble(a);
            double valorB = Convert.ToDouble(b);
            double valorX = Convert.ToDouble(x);
            double valorY = Convert.ToDouble(y);
            double valorN = Convert.ToDouble(n);

            double valorPrimeraParte = (valorA * valorX);
            double valorSegundaParte =  ( valorB * valorY);
            double valorParcial = valorPrimeraParte + valorSegundaParte;
            totalEsperado = valorParcial * valorParcial;
        }

        public void OnGet()
        {
        }
    }
}

IntroduccionRazor/Pages/HolaMundoRazor.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace IntroduccionRazor.Pages
{
    public class HolaMundoRazorModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

IntroduccionRazor/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace IntroduccionRazor.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

IntroduccionRazor/Pages/MensajeSecreto.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace IntroduccionRazor.Pages
{
    public class MensajeSecretoModel : PageModel
    {
        [BindProperty]
        public string mensajeOriginal { get; set; }

        [BindProperty]
        public int n { get; set; }

        public string mensajeCodificado { get; set; }
        public string mensajeDecodificado { get; set; }  // Agrega esta propiedad para mostrar el mensaje decodificado

        public void OnPost()
        {
            mensajeOriginal = Request.Form["mensajeOriginal"];
        }

        public void OnPostDecodificar()
        {
            mensajeCodificado = Request.Form["mensajeCodificado"]; 
            n = int.Parse(Request.Form["n"]);  

            mensajeDecodificado = DecodeMessage(mensajeCodificado, n); 
        }

        public void OnGet()
        {
            mensajeOriginal = "";
        }

        private string DecodeMessage(string mensajeCodificado, int n)
        {
            string mensajeMayusculas = mensajeCodificado.ToUpper();
            string mensajeDecodificado = "";

            for (int i = 0; i < mensajeMayusculas.Length; i++)
            {
                char letraOriginal = mensajeMayusculas[i];
                if (letraOriginal == 'U')
                {
                    letraOriginal = 'T';
                }

                if (char.IsLetter(letraOriginal))
                {
                    int posicionAbecedario = letraOriginal - 'A';
                    int nuevaPosicion = (posicionAbecedario - n + 25) % 25;
                    char letraDecodificada = (char)('A' + nuevaPosicion);
                    mensajeDecodificado += letraDecodificada;
                }
                else
                {
                    mensajeDecodificado += letraOriginal;
                }
            }

            return mensajeDecodificado;
        }
    }
}

IntroduccionRazor/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace IntroduccionRazor.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }

}

IntroduccionRazor/Pages/SintaxisBasica.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace IntroduccionRazor.Pages
{
    public class SintaxisBasicaModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

IntroduccionRazor/Pages/SumaFormulario.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Cryptography.X509Certificates;

namespace IntroduccionRazor.Pages
{
    public class SumaFormularioModel : PageModel
    {
        //Definimos los atributos
        [BindProperty]
        public string num1 { get; set; } = "";

        [BindProperty]
        public string num2 { get; set; } = "";

        public double suma = 0;


        public void OnPost()
        {
            double numero1 = Convert.ToDouble(num1);
            double numero2 = Convert.ToDouble(num2);

            suma = numero1 + numero2;

            ModelState.Clear();
        }

        public void OnGet()
        {
            
        }
    }
}

IntroduccionRazor/Pages/Arreglos.cshtml
@page
@model IntroduccionRazor.Pages.ArreglosModel
@{
    //Arreglo de string
    string[] nombres = ["Ana", "Juan", "Pedro", "María"];

    //Obtenemos la posición de Pedro.
    int i = Array.IndexOf(nombres, "Pedro") + 1;

    //Longitud del arreglo
    int len = nombres.Length;
    string segundo = nombres[1];
}

<h3>Lista de Nombres en el arreglo.</h3>

<ol>
    @foreach(var nombre in nombres)
    {
        <li>@nombre</li>
    }
</ol>

<p>El número de personas en nombres es: @len</p>

<br />


<p>La persona en la segunda posición es: @segundo</p>

<br />

<p>Pedro está en la posición: @i</p>

IntroduccionRazor/Pages/ArreglosNum.cshtml
@page
@model IntroduccionRazor.Pages.ArreglosNumModel
@{
    ViewData["Title"] = "Arreglos";
}

<style>
    .horizontal-list {
        display: flex;
        list-style-type: none;
        padding: 0;
    }

    .horizontal-list li {
        margin-right: 10px;
    }
</style>

<h1>Números Aleatorios</h1>

<ul class="horizontal-list">
    @foreach (var numero in Model.numeros)
    {
        <li>@numero</li>
    }
</ul>
<br />
<br />

@{
    int suma = 0;
    for (int i = 0; i < Model.numeros.Length; i++)
    {
        suma += Model.numeros[i];
    }
}

<h1>La suma de los números del arreglo es: @suma</h1>

@{
    float promedio = (float)suma / Model.numeros.Length; // División flotante para obtener el promedio como decimal
}

<h1>La media aritmética es de: @promedio</h1>

@{
    int[] frecuencia = new int[101]; // Array para contar la frecuencia de cada número del 0 al 100
    foreach (var numero in Model.numeros)
    {
        frecuencia[numero]++;
    }

    int moda = -1;
    int maxFrecuencia = 0;
    for (int i = 0; i <= 100; i++)
    {
        if (frecuencia[i] > maxFrecuencia)
        {
            moda = i;
            maxFrecuencia = frecuencia[i];
        }
    }

    if (maxFrecuencia == 1)
    {
        <h1>Todos los números aparecen una vez, no hay moda.</h1>
    }
    else
    {
        <h1>La moda (el número que más se repite) es: @moda</h1>
        <h1>Se repite @maxFrecuencia veces.</h1>
    }
}

@{
    int[] numerosOrdenados = Model.numeros.OrderBy(n => n).ToArray();
    float mediana = 0;

    if (numerosOrdenados.Length % 2 == 0)
    {
        int indice1 = numerosOrdenados.Length / 2 - 1;
        int indice2 = numerosOrdenados.Length / 2;
        mediana = (float)(numerosOrdenados[indice1] + numerosOrdenados[indice2]) / 2;
    }
    else
    {
        int indice = numerosOrdenados.Length / 2;
        mediana = numerosOrdenados[indice];
    }
}

<h1>Los números ordenados son:</h1>
<ul class="horizontal-list">
    @foreach (var numero in numerosOrdenados)
    {
        <li>@numero</li>
    }
</ul>
<h1>La mediana (número medio) es: @mediana</h1>

IntroduccionRazor/Pages/Ciclos.cshtml
@page
@model IntroduccionRazor.Pages.CiclosModel

<h3>Ciclo While</h3>
@{
    var cont1 = 1;
    while (cont1 < 10)
    {
        <p>@cont1</p>
        cont1++;
    }
}

<br />

<h3>Ciclo Do While</h3>
@{
    var cont2 = 1;
    do
    {
        <p>@cont2</p>
        cont2++;
    } while (cont2 < 10);
}

<br />

<h3>Ciclo For</h3>
@{
    for (var cont3 = 0; cont3 < 21; cont3++)
    {
        <p>@cont3</p>
    }
}

<br />

<h3>Ciclo for-each en Headers</h3>
<ul>
    @foreach (var x in HttpContext.Request.Headers)
    {
        <li>@x.Key: @x.Value</li>
    }
</ul>

IntroduccionRazor/Pages/Condicionales.cshtml
@page
@model IntroduccionRazor.Pages.CondicionalesModel
@{
    var calificacion = 8;
    var precio = 25;
}
<h3>Instrucciones condicionales</h3>
<p>Tu calificación es de: @calificacion</p>

@if(calificacion >= 8)
    {
        <p>Ya pasaste</p>
    }
    else
    {
        <p>Estás en recuperación</p>
    }
<br />

<h3>Estructuras condicionales if - else</h3>

@if(precio >= 30)
{
    <p>El precio es alto</p>
}
else if(precio > 20 && precio < 30)
{
    <p>El precio es normnal</p>
}
else
{
    <p>El precio es bajo</p>
}
<br />

<h3>Estructuras condicionales Múltiples Switch-Case</h3>

@{
    var diaSemana = DateTime.Now.DayOfWeek;
    var dia = diaSemana.ToString();
    var mensaje = "";
}

@switch (dia)
{
    case "Monday":
        mensaje = "Este es el primer día de la semana";
        break;
    case "Thursday":
        mensaje = "Solo falta un día para el viernes";
        break;
    case "Friday":
        mensaje = "Hoy es viernes y el cuerpo...";
        break;
    default:
        mensaje = "Un día más de la semana";
        break;
}

<p>@mensaje</p>

IntroduccionRazor/Pages/Expresion.cshtml
@page
@using System.Numerics
@model IntroduccionRazor.Pages.ExpresionModel

<h1>Calcula una expresión</h1>

<form method="post">
    <label asp-for="a">Valor de a: </label><br>
    <input type="text" asp-for="a" /><br>

    <label asp-for="b">Valor de b:</label><br>
    <input type="text" asp-for="b" /><br>

    <label asp-for="x">Valor de x:</label><br>
    <input type="text" asp-for="x" /><br>

    <label asp-for="y">Valor de y:</label><br>
    <input type="text" asp-for="y" /><br>

    <label asp-for="n">Valor de n:</label><br>
    <input type="text" asp-for="n" /><br><br />

    <input type="submit" value="Calcular"><br /><br />
</form>

@{
    <h1>El valor esperado es: </h1>
    <h3>@Model.totalEsperado</h3>
    <br />
    <br />

    <h1>Factorial y sumatoria: </h1>
    int nReal = @Model.n;
    double totalSumatorio = 0;
    double total = 0;

    for (var k = 0; k <= nReal; k++)
    {
        double nFactorial = 1;
        double kFactorial = 1;
        double nMinusKFactorial = 1;

        for (double i = 1; i <= nReal; i++)
        {
            nFactorial *= i;
            if (i <= k)
            {
                kFactorial *= i;
            }
            if (i <= (nReal - k))
            {
                nMinusKFactorial *= i;
            }
        }

        double resultadoReal = nFactorial / (kFactorial * nMinusKFactorial);
        totalSumatorio += resultadoReal;

        double ax = (Model.a * Model.x);
        double by = (Model.b * Model.y);
        double res = resultadoReal * Math.Pow(ax, nReal - k) * Math.Pow(by, k);

        <p>Para n = @nReal y k = @k, el resultado de la factorial es: @resultadoReal</p>
        <p>El resultado de la fórmula es: @res</p>
        total += res;
    }
    <h3>El valor total sumatorio para n = @nReal es: @total</h3>
}

IntroduccionRazor/Pages/HolaMundoRazor.cshtml
@page
@model IntroduccionRazor.Pages.HolaMundoRazorModel
@{
    ViewData["Title"] = "Hola mundo";
}

<!-- Escribimos un mensaje utilizando sintaxis de Razor -->

@{
    var mensaje = "Hola mundo desde ASP .NET Core";
}

<p>Este es un mensaje de Bienvenida @mensaje</p>

IntroduccionRazor/Pages/IMC.cshtml
@page
@model IntroduccionRazor.Pages.IMCModel

<h2>Calcula tu IMC</h2>
<form method="post">
    <label asp-for="peso">Ingresa tu peso:</label>
    <input type="text" asp-for="peso" name="peso" value="" placeholder="Ingresalo en kg" />
    <br />

    <label asp-for="estatura">Ingresa tu estatura:</label>
    <input type="text" asp-for="estatura" name="estatura" value="" placeholder="Ingresala en metros" />
    <br />

    <p><input type="submit" value="Calcular" /></p>
</form>

@if (Model.Resultado != 0)
{
    <strong>Tu IMC de @Model.Resultado</strong>
    <br />

    @switch (Model.Resultado)
    {
        case float value when value < 18:
            <strong>Tu peso es bajo</strong>
            <br />
            <img src="~/images/subirpeso.jpg" style="width: 250px; height: 250px;" />
            break;
        case float value when value >= 18 && value < 25:
            <strong>Tu peso es normal</strong>
            <br />
            <img src="~/images/pesomantener.webp" style="width: 250px; height: 250px;" />
            break;
        case float value when value >= 25 && value < 27:
            <strong>Tienes sobrepeso</strong>
            <br />
            <img src="~/images/sobrepeso.jpg" style="width: 250px; height: 250px;" />
            break;
        case float value when value >= 27 && value < 30:
            <strong>Tienes obesidad grado 1</strong>
            <br />
            <img src="~/images/obesidad.jpg" style="width: 250px; height: 250px;" />
            break;
        case float value when value >= 30 && value < 40:
            <strong>Tienes obesidad grado 2</strong>
            <br />
            <img src="~/images/obesidad1.jpg" style="width: 250px; height: 250px;" />
            break;
        default:
            <strong>Tienes obesidad grado 3</strong>
            <br />
            <img src="~/images/obesidad3.jpg" style="width: 250px; height: 250px;" />
            break;
    }
}
else
{
    <strong>Aquí aparecerá tu resultado</strong>
}

IntroduccionRazor/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

IntroduccionRazor/Pages/MensajeSecreto.cshtml
@page
@model IntroduccionRazor.Pages.MensajeSecretoModel
@{
}

<h1>Convierte tu mensaje en secreto</h1>

<form method="post">
    <label asp-for="mensajeOriginal">Mensaje:</label><br>
    <textarea asp-for="mensajeOriginal" id="mensaje" name="mensajeOriginal" rows="4" cols="50"></textarea><br>
    <label asp-for="n">Valor de n:</label>
    <input type="number" asp-for="n" id="n" name="n" min="1"><br><br>
    <input type="submit" value="Codificar">
</form>

<!-- Mostrar el mensaje original -->
@if (!string.IsNullOrEmpty(Model.mensajeOriginal))
{
    <h1>Mensaje Original:</h1>
    <h3>@Model.mensajeOriginal</h3>
}

@{
    string mensajeMayusculas = Model.mensajeOriginal.ToUpper();
    string mensajeCodificado = "";

    int n = Model.n;

    for (int i = 0; i < mensajeMayusculas.Length; i++)
    {
        char letraOriginal = mensajeMayusculas[i];

        if (char.IsLetter(letraOriginal))
        {
            int posicionAbecedario = letraOriginal - 'A';

            int nuevaPosicion = (posicionAbecedario + n) % 26;

            char letraCodificada = (char)('A' + nuevaPosicion);

            if (letraCodificada == 'W')
            {
                letraCodificada = 'X';
            }

            mensajeCodificado += letraCodificada;
        }
        else
        {
            mensajeCodificado += letraOriginal;
        }
    }
}

<h1>Mensaje Codificado:</h1>
<h3>@mensajeCodificado</h3>

<br />
<br />

<h1>Decodifica tu mensaje secreto</h1>

<form method="post" asp-page-handler="Decodificar">
    <input type="hidden" asp-for="mensajeOriginal" />
    <label asp-for="mensajeCodificado">Mensaje Codificado:</label><br>
    <textarea asp-for="mensajeCodificado" id="mensajeCodificado" name="mensajeCodificado" rows="4" cols="50"></textarea><br>
    <label asp-for="n">Valor de n:</label>
    <input type="number" asp-for="n" id="n" name="n" min="1"><br><br>
    <input type="submit" value="Decodificar">
</form>

<h1>Mensaje Decodificado:</h1>
@if (!string.IsNullOrEmpty(Model.mensajeDecodificado))
{
    <h3>@Model.mensajeDecodificado</h3>
}

@functions {
    private string DecodeMessage(string mensajeCodificado, int n)
    {
        string mensajeMayusculas = mensajeCodificado.ToUpper();
        string mensajeDecodificado = "";

        for (int i = 0; i < mensajeMayusculas.Length; i++)
        {
            char letraOriginal = mensajeMayusculas[i];

            if (char.IsLetter(letraOriginal))
            {
                int posicionAbecedario = letraOriginal - 'A';
                int nuevaPosicion = (posicionAbecedario - n + 26) % 26;
                char letraDecodificada = (char)('A' + nuevaPosicion);
                mensajeDecodificado += letraDecodificada;
            }
            else
            {
                mensajeDecodificado += letraOriginal;
            }
        }

        return mensajeDecodificado;
    }
}

IntroduccionRazor/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/IntroduccionRazor.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">IntroduccionRazor</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li><li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/IMC">IMC</a>
                        </li>
                            <a class="nav-link text-dark" asp-area="" asp-page="/MensajeSecreto">Mensaje Secreto</a>
                        </li>
                        <li>
                        <a class="nav-link text-dark" asp-area="" asp-page="/Expresion">Expresión</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-page="/ArreglosNum">Arreglos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - IntroduccionRazor - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

IntroduccionRazor/Pages/SintaxisBasica.cshtml
@page
@model IntroduccionRazor.Pages.SintaxisBasicaModel
@{
}

@{
    var nombre = "Lorena";
}

<p>El valor de la variable nombre es: @nombre</p>

<!-- Bloque de código -->

@{
    var biencenida = " Bienvenido(a) a nuestro Sitio";
    var diaSemana = DateTime.Now.DayOfWeek;
    var mensajeBienvenida = biencenida + " Aquí en León es: " + diaSemana;
    var edad = 18;
}

<p>El mensaje de bienvenida es: @mensajeBienvenida</p>

IntroduccionRazor/Pages/SumaFormulario.cshtml
@page
@model IntroduccionRazor.Pages.SumaFormularioModel
@{
}

<h3>Suma de dos números</h3>

<form method="post">
    <p>Número 1: <input type="number" asp-for="num1"/></p>
    <p>Número 2: <input type="number" asp-for="num2"/></p>
    <p><input type="submit" value="Calcular"/></p>

    @if(Model.suma != 0)
    {
        <div>
            <strong>Suma = @Model.suma</strong>
        </div>
    }
</form>